version: '3'
  services:
    nginx:
          image: nginx:latest
          ports:
              - "80:80"
              - "443:443"
          volumes:
              - ./hosts:/etc/nginx/conf.d
              - ./www:/var/www
              - ./logs:/var/log/nginx
